spring:
  thymeleaf:
    cache: false
    mode: HTML5

 #设置静态资源的请求路径
spring:
  mvc:
    static-path-pattern: /**
#指定静态资源的路径
spring:
  resources:
    static-locations=classpath: /static/


#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.demo.entity
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/tasks
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

